import React from "react";

const Privacy = () => {
  return (
    <div className=" flex items-center justify-center min-h-screen">
      <main className=" shadow-md rounded-lg max-w-3xl w-full p-8">
        <section>
          <h1 className="text-3xl font-bold text-start mb-4">Privacy Policy</h1>
          <article className="text-gray-400">
            <h2 className="text-xl font-semibold mb-2">1. Introduction</h2>
            <p className="mb-4">
              At [Project Name], we respect your privacy and are committed to
              protecting your personal data. This Privacy Policy explains how we
              collect, use, and share your information when you use our
              services.
            </p>
            <h2 className="text-xl font-semibold mb-2">
              2. Information We Collect
            </h2>
            <p className="mb-4">
              <strong>Personal Information:</strong> We collect personal
              information that you provide directly to us, such as your name,
              email address, and any other information you choose to provide.
              <br />
              <strong>Usage Information:</strong> We collect information about
              your interactions with our services, such as the pages you visit
              and the features you use.
              <br />
              <strong>Content Data:</strong> We collect data and content
              generated by you using Google AI API through our services.
              <br />
              <strong>Technical Information:</strong> We collect technical
              information, such as your IP address, browser type, device used,
              and other technical data.
            </p>
          </article>
        </section>
      </main>
    </div>
  );
};

export default Privacy;
