import React from "react";

const Terms = () => {
  return (
    <div className=" flex items-center justify-center min-h-screen">
      <main className=" shadow-md rounded-lg max-w-3xl w-full p-8">
        <section className="mb-8">
          <h1 className="text-3xl font-bold text-start mb-4">
            Terms and Conditions
          </h1>
          <article className="text-gray-400">
            <h2 className="text-xl font-semibold mb-2">1. Introduction</h2>
            <p className="mb-4">
              Welcome to [Project Name]. These Terms and Conditions govern your
              use of our website and services. By accessing or using our
              platform, you agree to these terms in full.
            </p>
            <h2 className="text-xl font-semibold mb-2">2. Definitions</h2>
            <p className="mb-4">
              <strong>User:</strong> Any person who accesses and uses the
              services of [Project Name].
              <br />
              <strong>Content:</strong> Any information, text, graphics, or data
              generated by the User or through Google AI API via our service.
              <br />
              <strong>Services:</strong> All functionalities offered by [Project
              Name], including content generation through Google AI API.
            </p>
          </article>
        </section>

      
      </main>
    </div>
  );
};

export default Terms;
